append_commit_message: 
commit_message: 'l10n | Enhancement | %language% [skip ci]'
pull_request_title: "l10n | Enhancement"
export_languages:                          
  - 'zh-CN'
  - 'zh-TW'
  - 'no'
  - 'id'
  - 'es-ES'
  - 'de'
  - 'pt-BR'
  - 'uk'
  - 'fr'
  - 'it'
  - 'ru'
  - 'nl'
  - 'be'
  - 'be-BY'
  - 'be-rBY'
files:
  - source: /localization/src/main/res/values/strings.xml
    translation: /localization/src/main/res/values-%android_code%/strings.xml
