package com.anytypeio.anytype.core_models

enum class SmartBlockType {
    BREADCRUMBS,
    PAGE,
    PROFILE_PAGE,
    HOME,
    ARCHIVE,
    SET,
    BUNDLED_OBJECT_TYPE,
    CUSTOM_OBJECT_TYPE,
    FILE,
    TEMPLATE,
    MARKETPLACE_TYPE,
    MARKETPLACE_RELATION,
    MARKETPLACE_TEMPLATE,
    BUNDLED_RELATION,
    INDEXED_RELATION,
    ANYTYPE_PROFILE,
    DATABASE,
    BUNDLED_TEMPLATE,
    DATE,
    WORKSPACE
}