package com.anytypeio.anytype.presentation.objects.custom_icon

/**
 * Data class representing a custom icon.
 * @property rawValue The raw string representing the icon.
 */
data class CustomIcon(val rawValue: String) {
    /**
     * Returns the drawable resource name for this icon.
     *
     * The drawable name is generated by converting [rawValue] to snake case and
     * prefixing it with "ci_". For example, "batteryDead" becomes "ci_battery_dead".
     */
    val drawableName: String
        get() = "ci_" + rawValue.toSnakeCase()
}

/**
 * Extension function that converts a string from camel case to snake case.
 *
 * Iterates over each character of the string, inserting an underscore before uppercase
 * characters (except for the first character) and converting them to lowercase.
 *
 * @receiver String to be converted.
 * @return The snake case version of the string.
 */
private fun String.toSnakeCase(): String {
    return fold(StringBuilder()) { acc, c ->
        if (c.isUpperCase()) {
            if (acc.isNotEmpty()) acc.append('_')
            acc.append(c.lowercaseChar())
        } else {
            acc.append(c)
        }
        acc
    }.toString()
}