name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - name: Get Org Members
        id: members
        uses: octokit/request-action@v2.x
        with:
          route: GET /orgs/anyproto/members
        env:
          GITHUB_TOKEN: ${{ secrets.ANY_CLA_TOKEN }}

      - name: Extract Member Logins
        run: |
          echo '${{ steps.members.outputs.data }}' | jq -r '.[].login' | tr '\n' ',' > members.txt
          echo "dependabot" >> members.txt
          echo "members=$(cat members.txt)" >> "$GITHUB_ENV"
          
      - name: CLA Assistant
        uses: contributor-assistant/github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.ANY_CLA_TOKEN }}
        with:
          custom-notsigned-prcomment: '<br/>Thank you for your pull request, we really appreciate it!<br/><br/>Please sign our [Contributor License Agreement](https://github.com/anyproto/open/blob/main/templates/CLA.md) before we can accept your contribution.<br/>You can sign the CLA by simply commenting on this pull request with the following text.<br/>'
          path-to-document: "https://github.com/anyproto/open/blob/main/templates/CLA.md"
          remote-organization-name: "anyproto"
          remote-repository-name: "cla"
          branch: "main"
          path-to-signatures: "signatures.json"
          allowlist: ${{ env.members }}
